### ISSUE TITLE
Decide on Services to offer

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/conglobo#11]
A Service is an application that a User can deploy on their underlying Kubernetes cluster. We should decide a list of Services to offer (even initially). This decision is important because:
* It impacts what supplementary Services we need. For example, do we need to run Posgres on the cluster as well? Ideally not
* We will need to create deployment methods for these Services. Projects may offer easy ways to deploy this onto Kubernetes

See this link for a list of "selfhosted" projects: https://github.com/awesome-selfhosted/awesome-selfhosted. We should document these characteristics:
* How secure is the project? We do have other layers of security (the VPN, specifically), so insecure projects are not the end of the world
* What does this project need? Dependencies include SQL, S3, and identity management.
* Could we develop a smaller equivalent of this app? Given our Users, they may not need complicated apps.
* How easy/hard is it to deploy to Kubernetes? 

3-5 services

# Todo
- [x] Think of general categories
- [ ] Come up with the list (and document characteristics)

**Comment by ehharvey** [comment]
# Categories
* NAS / Media Server: syncthing, pydio
* Social Media: Mastadon
* Data analysis: homebrew app (NLP, phone orientation)

**Comment by Gabeele** [comment]
![Image](https://user-images.githubusercontent.com/59030389/218616362-6a22f7c3-618f-4f46-a96b-0e2227b54cc6.png)
