### ISSUE TITLE
Figure out an easy way to test S3 locally (run a local S3/MinIO instance)

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/conglobo#32]
Ideas
* Docker container

**Comment by Gabeele** [comment]
Looks like minio has it's own server system which we can query. https://www.digitalocean.com/community/tutorials/how-to-set-up-minio-object-storage-server-in-standalone-mode-on-ubuntu-20-04

**Comment by Gabeele** [comment]
`minio server storage  --console-address :9090`
