### ISSUE TITLE
Integration management-app frontend and its API

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/conglobo#34]
- [x] Produce a docker image that has API, serves frontend
- [x] Make sure that frontend buttons send requests to backend, etc.

**Comment by Gabeele** [comment]
Set up the flask app to server the flutter files. There are a few pieces that should be added to make it more dynamic to the active-services. Below is a screen shot of the UI being served by flask. To have the system run:
1. run `flutter build web` in the frontend directory. This will build the web files for flask to serve. 
2. Move to the backend and run `python app.py` Then the server should be running locally on part 5000.

![image](https://user-images.githubusercontent.com/59030389/224403737-037eb9ab-0ac6-478c-94fa-4b71cd194e5f.png)

- [x] We should improve the enable disable buttons look
- [x] Have the names of the services not hard coded but derived from the json of the active services. 
- [x] Maybe we could fill out the setup UI with a simple input for title, description, and github? Just to have it for prototyping. 

This is the json with some example data. 
![image](https://user-images.githubusercontent.com/59030389/224404406-cd024821-ef05-4432-8e23-b784912192b5.png)

**Comment by Gabeele** [comment]
Added the dockerfile to build and checked if it runs. to build go to the `management-app` directory and run docker `build -t mamagment-app:latest .`. Next run the docker by using `docker run -p 8000:8000 managment-app:latest`.
